### ISSUE TITLE
Object to Tile Communication

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#177]
### Summary

Setup communication between structural objects and the tile manager.

### Goal 

Structural objects (turfs or fixtures) should be communicating with the tilemap.

"Currently turfs and fixtures have no way to communicate with their Tile Object or the Tile Manager, which is why when you delete a wall it doesn't update the surrounding walls or the tilemap." - Seteron

This is also the cause of bugs #146 and #147.

**Comment by TimFinucane** [comment]
This is very generic, and probably needs to be more specific about what actually needs to be implemented. Especially given that there are already ways to communicate

**Comment by cosmiccoincidence** [comment]
Fair enough. I personally wasn't sure how to elaborate on it in detail but wanted to at least get an issue started for it. If you are someone else wants to elaborate on it, feel free.

**Comment by henkhooft** [comment]
Communication is already in place however only if the TileObject is deleted. By default clicking on tile in the editor selects the Turf or Fixture, and not the TileObject that is one step higher. Normally the parent would be selected because the [SelectionBase] attribute is set in TileObject. 

However because both the turf and fixtures are instantiated as prefab, not as GameObject. This makes Unity ignore the [SelectionBase] attribute.

This line in EditorAndRuntime.cs causes the issue when in the editor:
`return (GameObject)PrefabUtility.InstantiatePrefab(gameObject);`

Instantiating it with the regular code solves this issue:
`return GameObject.Instantiate(gameObject, transform);`

So why is instantiating the prefab necessary in this way? If removed it would solve bugs #146 and #147 as it then correctly deletes the TileObject when removed.

**Comment by cosmiccoincidence** [comment]
Hi @henkhooft, feel free to PR this change if you are interested. Doing so would properly credit you for this fix.

**Comment by cosmiccoincidence** [comment]
Actually, upon attempting this change on one of my branches I got this error:
![image](https://user-images.githubusercontent.com/41941008/81873435-c2b4c700-9549-11ea-832c-845fdd9db91c.png)
