### ISSUE TITLE
Change container slot visuals

### ISSUE THREAD

**Issue by TaylorNAlbarnaz** [RE-SS3D/SS3D#332]
### Summary

Right now they look way too big and hard to see, see the image below as reference:
![image](https://user-images.githubusercontent.com/28792244/82843996-490bca00-9eb5-11ea-9ecd-6b1968cef93c.png)

### Goal 

Like in the image above, we'll need the following:
1- Right now the slot occupies over 13% of the screen's height in all cases, we want it to be about 65% of it's current size for the default ui(like Hands, etc) and 40% for containers like backpack slots
2- Openable Containers should show their ui on top of the current containers if on the inventory, or in the middle of the screen(on top of the Hands) in case of a external container
3-  They should have backgrounds around all slots instead of being just a transparent ui

**Comment by cosmiccoincidence** [comment]
Something else I notice about beeps is, occupied inventory slots have a dark background while unoccupied inventory slots do NOT have a dark background... the dark background is is nice for when it's occupied because it helps you see the item in the slot better, but it's nice not having a dark background on unoccupied slots to allow the users more visibility to the world behind the UI.
