### ISSUE TITLE
Tables not displaying connected mesh on host

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#402]
### Summary

Tables do not display a newly built/connected mesh when viewed from host.

### Steps to Reproduce

- Build the game and run 2 instances, 1 hosting, 1 joining
- Using the host, try to build a table and notice that you will not see the new mesh, although neighboring meshes will update still. Joining clients do not seem to have the issue. And walls do not seem effected either.

![image](https://user-images.githubusercontent.com/41941008/84732463-cdf47b80-af69-11ea-89d2-9caea4ab243d.png)

**Comment by Alainx277** [comment]
This is caused by a array comparison on fixtures. If the array has remained the same, the fixtures will not update.
Because the fixture array is directly accessed (and arrays are reference types) the check assumes nothing has changed.

It works on the client because the entire struct is serialized, which means the array is actually a different instance.
