### ISSUE TITLE
Airlock Click to Open

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#452]
Airlocks should be Openable and Closable via clicking or the interaction wheel... We had this at one point but it seems to have either been removed or broken.

**Comment by CrazyMalk** [comment]
The code is already implemented, but the airlock model is intercepting the click on the doors. Working on it

**Comment by CrazyMalk** [comment]
A little more debugging and the problem is that the door's BoxCollider is a trigger, and in the interaction code the raycast is set to ignore triggers. All that is needed is to allow trigger colliders to be interacted with, although I am unsure of why ignoring triggers is needed in the first place, so it might break stuff.
