### ISSUE TITLE
Door gets rotated by wrench

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#580]
### Current Behavior

When wrenching the floor beneath an airlock, the airlock will rotate to the vertical rotation position.

### Steps to Reproduce

Use a wrench on the floor beneath an airlock (if nothing happened, that airlock may already be in the vertical position, try another that is perpendicular).

### Expected Behavior

Nothing should happen when trying to wrench the floor beneath a door (maybe later this action will have some other function but for now it is not wanted).

**Comment by mjboth** [comment]
I looked into this, and it appears that it's not just doors, but all furniture and overlays on a tile.  Whenever the wrench is used on a tile it will reset all fixtures on top of it to face North.  I believe that this is caused somewhere down the UpdateTile function, but as of now I have been unable to pinpoint where the rotation variable is being reset.


https://user-images.githubusercontent.com/4644621/116478431-0d5b4c00-a84c-11eb-9d1a-05af8211718a.mp4


In addition, I have also found that the wrench will create a table over a cryotube.  This is because the cryotube is declared as "Pipe Upper" instead of "Furniture Main."  Since there is officially no furniture on the tile, it is declared vacant and will build a table on top of it.


https://user-images.githubusercontent.com/4644621/116478981-f2d5a280-a84c-11eb-8281-cc5c05ea7e41.mp4

**Comment by cosmiccoincidence** [comment]
Wew lad, this is interesting. Thanks for looking into this. The cryotube thing will likely get fixed later on when we can set it to Furniture Main and maybe have a component that also shows up on Pipe Upper in order to properly trigger the pipe connector.

**Comment by cosmiccoincidence** [comment]
After some recent changes this bug needs to be confirmed again.

**Comment by cosmiccoincidence** [comment]
seems related to #486

**Comment by mjboth** [comment]
I can confirm that the bug still exists.  The wrench will still reset all furniture fixtures to face North.
It also appears that all doors are now facing North the current master branch.


https://user-images.githubusercontent.com/4644621/123209432-91b5fe00-d48e-11eb-8e97-e1c49e0cc2f9.mp4


I also just noticed that using a wrench on a tile will reset all animations tied to it.


https://user-images.githubusercontent.com/4644621/123209640-e9546980-d48e-11eb-9553-1da3d7eaf241.mp4

**Comment by cosmiccoincidence** [comment]
> I can confirm that the bug still exists. The wrench will still reset all furniture fixtures to face North.

Maybe this is due to the Fixture State Orientation script. 

> It also appears that all doors are now facing North the current master branch.

This *should* be fixed in my PR #718

**Comment by mjboth** [comment]
This is the latest version of the master branch running in Unity

**Comment by cosmiccoincidence** [comment]
> This is the latest version of the master branch running in Unity

0.3.95d

The reason it is important to add this is so that 6 months in the future when someone tries to fix this, they will have some perspective of when this happened. Sometimes the status bugs/issues change over time with newer releases of the game too, so it good practice documenting the version number. Something we haven't been doing until VERY recently but I'm beginning to enforce.

**Comment by mjboth** [comment]
I understand.  I'll be sure to keep this in mind for the future

**Comment by cosmiccoincidence** [comment]
Related to #628
