### ISSUE TITLE
Certain Tiles not loading on Clients

### ISSUE THREAD

**Issue by mjboth** [RE-SS3D/SS3D#705]
### Summary

Some of the tiles in the medical room will not load for clients connecting to the host 

### Current Behavior

After connecting to the host and loading into the game.  The tiles in the medical room will not load for connected clients.  It's the same tiles that go missing every time.

https://user-images.githubusercontent.com/4644621/121850467-d1286180-ccba-11eb-8570-4480befcf7e2.mp4

### Steps to Reproduce

1. Start two different instances of the game on the same computer.
2. Host a game on one instance and connect via localhost on the other.
3. Load up the MainStation map on host and start.
4. Send the connected client to the medical room and walk through missing walls.

### Possible Solution

I see that any tile that has a blue overlay is missing.  I don't know what could be causing the walls to fail to load, they appear to have nothing in common as far as I can tell.

### Context

Seen on v0.3.95d (but noticed on earlier versions at least as far back as v0.3.95b)

I can replicate the issue 100% of the time.

**Comment by Ryan089** [comment]
Hi @mjboth, thanks for taking the time to report this. This is a networking issue with our tilemap which we are aware of, and will be resolved by the reimplementation of tilemap in #628. I'm placing the 'Blocked' label on this issue so that no one tries to solve it in isolation, because their work would just be overwritten in the tilemap rework. I'll keep the issue open in the Redesign milestone so whoever re-implements the tilemap can use it as a reference if required.
