### ISSUE TITLE
[Task] Inventory Core 2: Multi-Container Manipulation

### ISSUE THREAD

**Issue by TimFinucane** [RE-SS3D/SS3D#73]
**Description**
- Have a way of moving items between containers on-screen.
- Create a container for holding clothing/items that go onto the body. 
  - items which go into the container should then appear on the player's body.

Current simplified item movement should be by click-drag, and/or by clicking an empty container slot. For players only an item currently being held can be placed anywhere. 

The body container should be heavily based on the existing HandsContainer, and in fact the HandsContainer should be generalised (e.g. to VisibleContainer) so that it both containers can be based off of it.

**Comment by onebigames** [comment]
As discussed, it seems more logical to implement the containers so that they are attached to items and/or specific body parts.
This would make it so when gaining or loosing an interactor(e.g arm) or a slot-providing equippable(e.g coat), the inventory's containers would react naturally and in a consistent manner.
