### ISSUE TITLE
Tilemap Movement & Rotation

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#785]
## Summary

The tilemap rework was recently completed and it should now be possible to move/rotate individual tilemaps from one another.

## Goal 

Using our current "MiniStation" map, implement basic movement and rotation of the 'shuttle' tilemap.

I'd maybe suggest attaching this mechanic to a computer console object for now and we can elaborate on it later.

**Comment by Birlinha** [comment]
Should this be a game mechanic?

Maybe this could be used by map developers, but I think this would break player immersion

In SS13, we have to build new rooms tile by tile
Maybe there could be a interface to "project" a new room, and then a robot (probably built by the boston dynamics roboticist in the station) could go and build the new room/new structure

Rotating an entire structure could maybe be more space immersive, like a docking simulator 

The minigame of piloting a floating tin can may be very exciting - Or extremely painful

**Comment by Birlinha** [comment]
What I mean by that is - I think different people will have fun with these mechanics in different ways:
- [ ] A roboticist will have fun creating machines that power up the station capability to auto-expand
- [x] A map developer will have a boost in productivity having a way to rotate and move an entire structure
- [ ] A pilot or any "flying" astronauts will have to deal with the lack of gravity to return to a station - with or without the structure/vehicle/plane they were hanging onto when drifting

Now, the last one is the most difficult one in my opinion - because I don't know much about game physics - I wouldn't know where to start

**Comment by Ryan089** [comment]
For this to work, we'd need to complete #791. I'm going to add the Blocked label, and reduce the priority accordingly.
