### ISSUE TITLE
Interactions on Toolbox don't always register

### ISSUE THREAD

**Issue by stilnat** [RE-SS3D/SS3D#807]
## Summary

With the client, interactions on the toolbox don't always register, no error messages. For example, trying to open the box sometimes fail. See [video](https://streamable.com/qvodj0). It seems to be specific to the toolbox though, I never experimented this issue with other containers. This happens in version 0.3.95g 

## Steps to Reproduce

grab a toolbox with the client and try to open a toolbox, sometimes it registers, sometime it doesn't. Same for the view interaction.

## Expected Behavior

All interaction should register.

**Comment by cosmiccoincidence** [comment]
The medkit works similarly. Would be worth trying to replicate the issue in that object as well.

Also, remember to add the game version in the issue incase this bug isn't resolved for a few months, then we will know when it occurred.

**Comment by J-DDog** [comment]
Seems to be only in the unity editor. Doesn't seem to happen in release build.

**Comment by Birlinha** [comment]
Left click on Closed-Toolbox >> Opens the container

![image](https://user-images.githubusercontent.com/47873385/132961823-ebf7380f-6402-43ec-aa25-1649bd4aa321.png)

-----------

Double Left Click on Closed-Toolbox >> Opens the container and the inventory inside of it

![image](https://user-images.githubusercontent.com/47873385/132961868-a9a79983-e9fc-4afc-9105-a1c39aaff44a.png)

-----------

Triple Left Click on Closed-Toolbox >> Opens the container and the inventory inside of it, then closes the Toolbox again

![image](https://user-images.githubusercontent.com/47873385/132961885-3949c212-070a-497e-89e5-cb098130422c.png)

-----------

Left Click on Open-Toolbox >> Opens the container inventory

Double Left Click on Open-Toolbox >> Opens Inventory then closes Container

(all the actions above have the same effect when clicking directly at the 3D Model, instead of the square in your hands - unless you change the hand you're using)

**Comment by Birlinha** [comment]
I tested out the containers you guys pointed out, everything seems to be working fine, I didn't understand what is the problem

I will make a quick video showing my interactions, but what I can say right now is that **multiple** interactions with containers all at the same time - like clicking 6+ times in a few seconds - can trigger the container open/close event a lot of times, and then the container doesn't do all the interactions

**Comment by Birlinha** [comment]
Test 1 --> Testing Left Click interactions with a Closed Toolbox
https://youtu.be/FUty0HiVTQc

**Comment by Ryan089** [comment]
@stilnat, I attempted to replicate the issue but could not. I used the 0.3.95g build published on github. I noticed that your video gives the interaction name as "open red toolbox", and my test gave the interaction name "open". Is this actually on your development branch? If so, perhaps this is a problem specific to that.

@Birlinha, I had some trouble reading the text on your video, but it seems like you weren't able to replicate nath's original issue. Can you confirm that you ran this on a client, rather than a host?

**Comment by Ryan089** [comment]
@stilnat, is this problem still occurring, or can this issue be closed?

**Comment by stilnat** [comment]
@Ryan089  we're good ! I tried it again and the way toolbox opens now make this bug completely outdated, if it even existed in the first place. I think I used to launch the client in the editor, that might be why it was so buggy.
