### ISSUE TITLE
Modding support

### ISSUE THREAD

**Issue by TimFinucane** [RE-SS3D/SS3D#86]
Figure out how servers can have modding support in the game

To consider:

- Do we want to provide tooling support and/or scripting support?
   - Easier for modders but is a lot of work to implement
- Alternatively, is it possible for modders to create something in unity that can act as a patch?

**Comment by birdbrainswagtrain** [comment]
As resident "failed clone idiot" I have strong opinions on modding (modding good). 

My knowledge on how to accomplish modding with unity is limited, but I'm currently looking at the Unity docs and how KSP and Cities Skylines accomplish it.

## Assets

Unity has [some support](https://docs.unity3d.com/Manual/LoadingResourcesatRuntime.html) for loading assets at runtime. People seem to recommend Asset Bundles, but they're apparently deprecated in favor of [addressable assets](https://docs.unity3d.com/Packages/com.unity.addressables@1.5/manual/index.html).

I'm not sure exactly what KSP is doing. It's mod tools use the unity editor and export files with an ".mu" extension which a lot of people seem to think is KSP-specific but might be some internal unity format. I'll investigate this more later.

Cities skylines has an in-game importer that imports FBX files. I don't think Unity is actually capable of loading other kinds of assets at runtime, so you'd probably have to link against ASSIMP or something similar if you wanted to do this kind of thing.

As much as I personally hate Unity, I figure it's best to use the tools it provides. I'll do some more digging to try and figure out a way to do this.

## Code

Loading .NET modules at runtime is probably the easiest way to accomplish modding with code. You might just be able to bundle these with whatever you use for asset loading, but I have some concerns with this.

One of the big issues with building a mod API is making it secure. If servers are able to dictate the code that clients run, doing malicious things can become trivially easy. I'm less concerned about server-side security. Server operators should generally know what they're doing, will probably be authoring the mods in the first place, and there are far fewer of them to target. There are a few ways to address security:
- Sandboxing: I know .NET has some support for Sandboxing via AppDomains, but they look like they might be more trouble than they're worth. You might also be able to scan the assemblies you load and use whitelist imports. Sandboxing is very difficult and there's a good chance that a sophisticated attack will find a way to break out of whatever jail you build.
- A Thin Client: This is possibly even more of a pain to implement. Basically, you don't let the client run *any* foreign code. In fact, you minimize pretty much everything that the client does. This could simplify the architecture of the game, but it's something you sort-of have to design the game around. It also limits being able to do more fancy clientside mods. I think this might be the best approach in theory, but I'm not willing to push for it hard enough to possibly turn the rest of the project into a dumpster-fire to facilitate it.
- A Scripting Engine: Scripting Engines usually have sandboxing built-in. The problem is that mods are now written in a different language from the game, which I don't think is a great idea. A statically typed language like C# is good for a project this large in scope, and most scripting engines are dynamically typed. You'll probably need to set up bindings for everything you want mods to be able to touch. There are Lua interpreters built for .NET which might be able to directly interface with C# code, but I'm skeptical of the performance and security of such projects.

Another thing to consider is whether you want to share mod code with clients. Some of the drama in the SS13 community seems to stem from features being stolen from different codebases. The usual way to fix this is to split client and server-side code, which is probably doable but also probably not worth the added complexity for anyone involved. Theft of code is not an issue with a thin client, but I'm not sure that's enough to make it the winning choice.

## Conclusion

My preference is to use the tools Unity provides for assets, try to find a way to sandbox assemblies, and don't worry about theft of code. Ideally mod developers should be able to just edit the existing Unity project and have it spit out the necessary assets and assemblies for clients to download. This is probably not possible, but it seems like something to shoot for. I'm willing to try to prototype such a system when I have the time.

**Comment by Alainx277** [comment]
It might be worth checking out [WebAssembly](https://webassembly.org/) for modding. There's already a C# implementation for [Wasmer](https://wasmer.io/) called [WasmerSharp](https://github.com/migueldeicaza/WasmerSharp). While WasmerSharp would make API integration tedious, it could be extended with annotations and automatic type mapping.

This would allow the mods to be written in multiple languages (every language you can compile to WebAssembly), and also make sure we have an efficient and sandboxed runtime. Stealing code won't be a problem, as only the assembly instructions can be recovered.

As for using Unity Asset Bundles/Modules, they're not really usable if security is a concern. Microsoft has deprecated assembly sandboxing almost completely. I also think there should be a easy way to extend the game and working with Unity directly may be difficult for beginners.

**Comment by Em3rgencyLT** [comment]
This might be controversial, but why do we need modding? If it is so that servers could run their own versions but player don't have to go find the client for that server each time, then there are other ways than modding to achieve this.

We could have a separate application to use as a server browser, which would download and launch the client of any given server. The server owners would have to provide a download link to their client, but otherwise could mod the code in whatever way they wanted. The benefits of that would be:
- Each server owner could modify their game and use all the same tools we used to create it
- We would not have to worry about modding support at all
- As far as the player is concerned, picking a server lets you join it, regardless of what version of the code is run on it

The potential downsides:
- Considerations for security. We would have to make sure the server owners are actually serving clients and not some malicious software
- The server browser would be separate software that we would have to host and maintain, etc.

**Comment by TimFinucane** [comment]
Modding support can mean a variety of things. The one I had most in mind when doing brief research on the subject was something like <https://forum.unity.com/threads/open-source-modtool-mod-support-for-unity.442185/>. From what it looks, the modding support that tool offers is that anyone can add new assets, prefabs, and code, and package those up into a mod that can be downloaded and applied over the original project.

This results in a solution effectively the same as the having-a-separate-browser, but means the user doesn't have to download the base game over and over.

**Comment by TheBricktop** [comment]
Yeah the modtool looks like the least problematic way to add mod support other than relying on open source structure of this project and custom forked clients and servers
